import json
import os

def update_json(filepath, new_entries):
    if not os.path.exists(filepath):
        data = {}
    else:
        with open(filepath, 'r', encoding='utf-8') as f:
            data = json.load(f)
    
    data.update(new_entries)
    
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=4)

# Batch 4b: 七年级上册 (N-Z)
g7_up_entries_nz = {
    "man": {"sentence": ["The tall man sitting near the window is our new English teacher.", "坐在窗口附近的那个高个子男人是我们的新英语老师。"]},
    "manager": {"sentence": ["My father is the manager of a big car factory in our city.", "我父亲是我们城市一家大汽车厂的经理。"]},
    "many": {"sentence": ["There are many tall trees and colorful flowers in the park.", "公园里有许多高树和彩色的花。"]},
    "many kinds of": {"sentence": ["There are many kinds of animals living in the large forest.", "茂密的森林里生活着多种动物。"]},
    "map": {"sentence": ["There is a big map of China on the wall of our classroom.", "我们教室的墙上挂着一幅巨大的中国地图。"]},
    "match": {"sentence": ["Did you watch the exciting football match on TV last night?", "昨晚你从电视上看那场精彩的足球赛了吗？"]},
    "maths": {"sentence": ["Maths is an important subject and it helps us solve problems.", "数学是一门重要的学科，它能帮我们解决问题。"]},
    "meat": {"sentence": ["Lions like to eat meat and they are very strong animals.", "狮子喜欢吃肉，它们是非常强壮的动物。"]},
    "merry": {"sentence": ["Everyone had a merry time at the birthday party yesterday.", "昨天生日聚会上每个人都过得很愉快。"]},
    "Merry Christmas": {"sentence": ["- Merry Christmas to you! - Merry Christmas, thank you very much.", "—祝你圣诞快乐！—圣诞快乐，非常感谢。"]},
    "middle": {"sentence": ["Our school is in the middle of a peaceful and small town.", "我们的学校在一个宁静小镇的中心。"]},
    "milk": {"sentence": ["I usually have a glass of warm milk for breakfast every day.", "我通常每天早餐喝一杯温牛奶。"]},
    "minute": {"sentence": ["Wait for me for a minute; I will be ready to go out soon.", "等我一分钟；我很快就准备好出门了。"]},
    "money": {"sentence": ["I saved some money to buy a special gift for my mother.", "我存了一些钱为我妈妈买了一份特别的礼物。"]},
    "monkey": {"sentence": ["The monkey is jumping happily among the trees in the forest.", "猴子正在森林的树丛间开心地跳跃。"]},
    "mother": {"sentence": ["My mother is a teacher and she works very hard every day.", "我母亲是一名老师，她每天工作都很努力。"]},
    "mouse": {"sentence": ["The cat is running fast to catch the small grey mouse.", "猫正飞快地跑着去捉那只灰色的小老鼠。"]},
    "movie": {"sentence": ["Let's go to the cinema to watch an exciting movie tonight.", "让我们今晚去电影院看场精彩的电影吧。"]},
    "Ms": {"sentence": ["Ms Li is our new English teacher and she is very friendly.", "李女士是我们的新英语老师，她非常友好。"]},
    "much": {"sentence": ["Thank you very much for your help with my English study.", "非常感谢你对我的英语学习提供的帮助。"]},
    "mum": {"sentence": ["Mum, can I have some orange juice and a small cake, please?", "妈妈，我能喝点橙汁并吃个小蛋糕吗？"]},
    "music": {"sentence": ["I like listening to music while I am doing my homework.", "我喜欢在做作业时听音乐。"]},
    "near": {"sentence": ["I live in a peaceful house near the old school library.", "我住在一所靠近老学校图书馆的宁静房子里。"]},
    "never": {"sentence": ["He is a hardworking student and never comes late for school.", "他是个努力的学生，上学从不迟到。"]},
    "next": {"sentence": ["What are you going to do during the next summer holiday?", "下个暑假你打算做什么？"]},
    "next to": {"sentence": ["The bank is right next to the big supermarket in our city.", "银行就在城市的大超市隔壁。"]},
    "night": {"sentence": ["The stars are very bright in the dark and clear night sky.", "在黑暗晴朗的夜空中，星星非常明亮。"]},
    "ninety": {"sentence": ["There are about ninety students in the school music club.", "学校音乐俱乐部大约有九十名学生。"]},
    "noodle": {"sentence": ["My mother cooks delicious beef noodles for us every weekend.", "我妈妈每个周末都为我们做美味的牛肉面。"]},
    "not": {"sentence": ["I am not a teacher; I am a student in the seventh grade.", "我不是老师；我是七年级的学生。"]},
    "nurse": {"sentence": ["His mother works as a nurse in a local city hospital now.", "他母亲现在在当地城市医院当一名护士。"]},
    "o'clock": {"sentence": ["I usually arrive at the school gate at seven o'clock sharp.", "我通常在七点整到达校门口。"]},
    "often": {"sentence": ["We often go to the library to study on Saturday afternoons.", "我们经常在周六下午去图书馆学习。"]},
    "oh": {"sentence": ["Oh! I forgot to bring my English textbook to school today.", "噢！我今天忘了带英语课本到学校。"]},
    "on sale": {"sentence": ["Many beautiful clothes in that shop are on sale this week.", "那家店的许多漂亮衣服本周在打折。"]},
    "on the left": {"sentence": ["The library is on the left side of the school playground.", "图书馆就在学校操场的左侧。"]},
    "on the right": {"sentence": ["The bank is just on the right corner of the busy street.", "银行就在繁华街道的右拐角处。"]},
    "or": {"sentence": ["Which do you prefer for lunch, beef noodles or fried rice?", "午饭你更喜欢哪种，牛肉面还是炒饭？"]},
    "our": {"sentence": ["Our school has a beautiful garden with many colorful flowers.", "我们的学校有一个长着许多彩色花的美丽花园。"]},
    "over there": {"sentence": ["Look! The tall boy standing over there is my cousin Tom.", "看！站在那边的那个高个子男孩是我的表弟汤姆。"]},
    "panda": {"sentence": ["Pandas are famous animals from China and they like bamboo.", "大熊猫是来自中国的著名动物，它们喜欢竹子。"]},
    "paper": {"sentence": ["Please write down your name and address on this piece of paper.", "请在这张纸上写下你的姓名和地址。"]},
    "parent": {"sentence": ["I usually have dinner with my parents at seven every night.", "我通常每晚七点和父母一起吃晚饭。"]},
    "park": {"sentence": ["My family often goes to the park for a walk on weekends.", "我们家人通常在周末去公园散步。"]},
    "party": {"sentence": ["We will have a big party to celebrate my thirteenth birthday.", "我们将办一个大派对来庆祝我十三岁的生日。"]},
    "PE": {"sentence": ["PE is my favourite subject because I like playing basketball.", "体育是我最喜欢的科目，因为我喜欢打篮球。"]},
    "people": {"sentence": ["The people in the small town are very friendly to visitors.", "小镇上的人对游客非常友好。"]},
    "photo": {"sentence": ["I took many beautiful photos during our trip to Beijing.", "在北京旅行期间，我拍了许多漂亮的照片。"]},
    "picture": {"sentence": ["There is a big picture of an elephant on the classroom wall.", "教室墙上挂着一幅巨大的象画。"]},
    "place": {"sentence": ["Beijing is a famous city with many interesting historical places.", "北京是一个有着许多有趣历史古迹的名城。"]},
    "plant": {"sentence": ["There are many green plants and tall trees in our garden.", "我们的花园里有许多绿植和高树。"]},
    "playground": {"sentence": ["The students are playing football happily on the playground.", "学生们正在操场上开心地踢足球。"]},
    "police": {"sentence": ["The police station is near the shopping mall in our city.", "警察局就在我们城市的购物商场附近。"]},
    "policeman": {"sentence": ["My uncle is a policeman and he works very hard every day.", "我叔叔是一名警察，他每天工作都很努力。"]},
    "potato": {"sentence": ["I like eating beef with potatoes for my dinner very much.", "我很喜欢晚饭吃牛肉炖土豆。"]},
    "print": {"sentence": ["Can you help me print this English article for our project?", "你能帮我为我们的项目打印这篇英语文章吗？"]},
    "programme": {"sentence": ["I like watching music programmes on TV on Friday nights.", "我喜欢在周五晚上从电视上看音乐节目。"]},
    "put away": {"sentence": ["Please put away your toys before you go to bed, little boy.", "小男孩，睡觉前请把你的玩具收起来。"]},
    "read": {"sentence": ["I like reading books about space and interesting animals.", "我喜欢读关于太空和有趣动物的书。"]},
    "rice": {"sentence": ["Most Chinese people like to eat rice for lunch and dinner.", "大多数中国人午饭和晚饭喜欢吃米饭。"]},
    "right": {"sentence": ["Go straight along this road and turn right at the corner.", "沿着这条路直走，在拐角处向右转。"]},
    "room": {"sentence": ["My room is small but very comfortable and always tidy.", "我的卧室虽然小，但非常舒适且总是很整洁。"]},
    "run": {"sentence": ["We like to run in the park together on Sunday mornings.", "我们喜欢在周日早晨一起去公园跑步。"]},
    "sale": {"sentence": ["There is a big sale in the supermarket near our school now.", "我们学校附近的超市现在正在大减价。"]},
    "scarf": {"sentence": ["She wore a red silk scarf to protect herself from the wind.", "她系着一条红色的丝绸围巾来防风。"]},
    "science": {"sentence": ["Science is an interesting subject about how the world works.", "科学是关于世界如何运作的一门有趣的学科。"]},
    "search for": {"sentence": ["I use the computer to search for information for my project.", "我用电脑为我的项目搜索信息。"]},
    "seventy": {"sentence": ["There are seventy students in the school art club this term.", "这学期学校艺术俱乐部有七十名学生。"]},
    "share": {"sentence": ["It is a good habit to share your toys with other children.", "和其他孩子分享玩具是一个好习惯。"]},
    "shoe": {"sentence": ["I bought a pair of new white shoes for the sports meet.", "我为校运会买了一双新的白鞋。"]},
    "shop": {"sentence": ["My mother often goes to the local fruit shop on weekends.", "我妈妈经常在周末去当地的水果店。"]},
    "silk": {"sentence": ["China is famous all over the world for its beautiful silk.", "中国以其美丽的丝绸享誉世界。"]},
    "sing": {"sentence": ["The little girl can sing English songs very beautifully now.", "那个小女孩现在能把英语歌唱得非常动听。"]},
    "sister": {"sentence": ["My older sister is a student in a city college in Beijing.", "我姐姐是北京一家城市学院的学生。"]},
    "sixty": {"sentence": ["There are sixty minutes in an hour and sixty seconds in a minute.", "一小时有六十分钟，一分钟有六十秒。"]},
    "sleep": {"sentence": ["Babies spend a lot of time in sleep every day and night.", "婴儿每天昼夜花很多时间睡觉。"]},
    "small": {"sentence": ["I live in a small but very peaceful village near the sea.", "我住在一个靠近大海但非常宁静的小村庄。"]},
    "so": {"sentence": ["It was raining, so we had to stay at home and read books.", "天在下雨，所以我们不得不待在家里看书。"]},
    "some": {"sentence": ["There are some beautiful flowers in our school garden now.", "现在我们学校的花园里有一些美丽的花。"]},
    "sometimes": {"sentence": ["Sometimes I go to the cinema with my best friends on Sundays.", "有时我周日和最好的朋友们一起去电影院。"]},
    "song": {"sentence": ["I like this English song very much because it is cheerful.", "我很喜欢这首英语歌，因为它很欢快。"]},
    "soup": {"sentence": ["I usually have a bowl of hot vegetable soup for my dinner.", "我晚饭通常喝一碗热蔬菜汤。"]},
    "speak": {"sentence": ["She can speak English very well after learning it for years.", "学习几年之后，她英语说得很好。"]},
    "spend": {"sentence": ["I spend about half an hour reading English every morning.", "我每天早晨化大约半小时读英语。"]},
    "star": {"sentence": ["The stars are very bright in the dark and clear night sky.", "在黑暗晴朗的夜空中，星星非常明亮。"]},
    "story": {"sentence": ["My grandfather has a lot of interesting stories about the past.", "我祖父有很多关于过去的有趣故事。"]},
    "strong": {"sentence": ["Doing more sports can help you become strong and healthy.", "多做运动能帮你变得强壮和健康。"]},
    "study": {"sentence": ["We should work hard and study to have a bright future.", "为了有一个美好的未来，我们应该努力学习。"]},
    "subject": {"sentence": ["What is your favourite subject? My favourite is English.", "你最喜欢的科目是什么？我最喜欢的是英语。"]},
    "such": {"sentence": ["I have never seen such a cute panda in the zoo before.", "以前我从未在动物园见过这么可爱的大熊猫。"]},
    "sun": {"sentence": ["The sun rises in the east and sets in the west every day.", "太阳每天从东方升起，从西方落下。"]},
    "sure": {"sentence": ["Are you sure about the result of the important math test?", "你确定那次重要数学测试的结果吗？"]},
    "sweater": {"sentence": ["Put on your sweater; it is getting cold outside this evening.", "穿上你的毛衣；今晚外面正变冷。"]},
    "sweep": {"sentence": ["We often sweep the classroom after school to keep it clean.", "放学后我们经常打扫教室以保持整洁。"]},
    "sweep away": {"sentence": ["The workers are busy trying to sweep away the thick snow.", "工人们正忙着清除厚雪。"]},
    "table": {"sentence": ["Please put the fruit and cakes on the small wooden table.", "请把水果和蛋糕放在那个小木桌上。"]},
    "take": {"sentence": ["Remember to take your schoolbag when you go to school.", "上学时记得带上你的书包。"]},
    "take photos": {"sentence": ["I like to take photos of beautiful flowers in the park.", "我喜欢在公园里拍漂亮的花的照片。"]},
    "talk": {"sentence": ["Please don't talk loudly while the teacher is speaking now.", "现在老师说话时请不要大声喧哗。"]},
    "tall": {"sentence": ["The tall boy standing near the library is my cousin Tom.", "站在图书馆附近的那个高个子男孩是我的表弟汤姆。"]},
    "tea": {"sentence": ["Many Chinese people like to drink hot tea after their dinner.", "许多中国人晚饭后喜欢喝热茶。"]},
    "television": {"sentence": ["We often watch football matches on television at weekends.", "我们经常在周末从电视上看足球赛。"]},
    "tell": {"sentence": ["Can you tell me the way to the nearest bus station, please?", "你能告诉我最近的车站怎么走吗？"]},
    "theatre": {"sentence": ["We went to a local theatre to watch a famous play yesterday.", "昨天我们去当地一段剧院看了一场著名的戏。"]},
    "their": {"sentence": ["The students are doing their homework in the quiet classroom.", "学生们在安静的教室里写作业。"]},
    "them": {"sentence": ["I found my lost keys; I left them on the small kitchen table.", "我找到了丢的钥匙；我把它们落在厨房小桌子上了。"]},
    "then": {"sentence": ["First finish your homework, and then you can go out to play.", "先完成作业，然后你可以出去玩。"]},
    "there": {"sentence": ["There are many tall trees and colorful flowers in the park.", "里有许多高树和彩色的花。"]},
    "these": {"sentence": ["These new English storybooks are very interesting for kids.", "这些新的英语故事书对孩子来说非常有趣。"]},
    "they": {"sentence": ["They are playing football happily on the school playground.", "他们正在学校操场上开心地踢足球。"]},
    "thing": {"sentence": ["I have many things to do during this busy winter holiday.", "在这个繁忙的寒假期间我有很多事情要做。"]},
    "think": {"sentence": ["I think learning English is very important for our future.", "我认为学习英语对我们的未来非常重要。"]},
    "thirty": {"sentence": ["There are thirty students in each small group for the project.", "项目的每个小组有三十名学生。"]},
    "those": {"sentence": ["Those red flowers in the garden smell very sweet and nice.", "花园里的那些红花闻起来非常香。"]},
    "tiger": {"sentence": ["The tiger is a very strong and famous animal in the world.", "虎是世界上的一种非常强壮且著名的动物。"]},
    "tired": {"sentence": ["He felt very tired after running for an hour in the park.", "在公园跑了一个小时后，他感到非常疲倦。"]},
    "to": {"sentence": ["I usually walk to the school library to read books after class.", "课后我通常步行去学校图书馆看书。"]},
    "tomato": {"sentence": ["My mother often cooks healthy tomato and egg soup for us.", "我妈妈经常为我们做健康的番茄鸡蛋汤。"]},
    "too much": {"sentence": ["Don't eat too much candy; it is not good for your health.", "别吃太多糖果；这对你的健康不好。"]},
    "tooth": {"sentence": ["Eating too much sweet candy is bad for your teeth and health.", "吃太多甜糖对你的牙齿和健康有害。"]},
    "train": {"sentence": ["We will take a train to Beijing during the summer holiday.", "暑假期间我们将坐火车去北京。"]},
    "travel": {"sentence": ["I hope to travel all over the world with my family one day.", "我希望有一天能和家人一起周游世界。"]},
    "tree": {"sentence": ["There are many tall trees and colorful flowers in the park.", "公园里有许多高树和彩色的花。"]},
    "turn": {"sentence": ["Go straight along this road and turn right at the corner.", "沿着这条路直走，在拐角处向右转。"]},
    "turn on": {"sentence": ["Please turn on the light; it's getting dark inside the room.", "请开灯；房间里正变暗。"]},
    "ugh": {"sentence": ["Ugh! This soup tastes very bad; please don't drink it.", "呃！这汤味道很差；请不要喝它。"]},
    "uncle": {"sentence": ["My uncle works in a big city and he often visits us here.", "我叔叔在大城市工作，他经常来这里看我们。"]},
    "use": {"sentence": ["We use the computer to look up information for our project.", "我们用电脑为我们的项目查找信息。"]},
    "vegetable": {"sentence": ["Eating more vegetables and fruit is good for a healthy life.", "多吃蔬果有利于健康生活。"]},
    "very": {"sentence": ["English is a very important language used all over the world.", "英语是一门在全世界都很受欢迎的重要语言。"]},
    "visit": {"sentence": ["We decided to visit the history museum this Sunday morning.", "我们决定本周日早晨参观历史博物馆。"]},
    "wait": {"sentence": ["Please wait for me at the school gate at four o'clock sharp.", "请四点整在校门口等我。"]},
    "wait for": {"sentence": ["I usually wait for the school bus at the stop near my house.", "我通常在离我家很近的车站等校车。"]},
    "walk": {"sentence": ["We like to walk in the park to enjoy the fresh air after dinner.", "我们喜欢在晚饭后去公园散步以享受新鲜空气。"]},
    "wall": {"sentence": ["There is a big map of the world on the wall of our classroom.", "我们教室的墙上挂着一幅巨大的世界地图。"]},
    "want": {"sentence": ["I want to be a famous doctor and help people in the future.", "我想成为一名著名的医生，将来帮助人们。"]},
    "wash": {"sentence": ["Remember to wash your hands before you have dinner, Tom.", "汤姆，记得在吃晚饭前洗手。"]},
    "watch": {"sentence": ["We like to watch football matches on TV together on weekends.", "我们喜欢在周末一起从电视上看足球赛。"]},
    "water": {"sentence": ["We should drink plenty of fresh water to stay healthy.", "我们应该喝充足的新鲜水以保持健康。"]},
    "we": {"sentence": ["We often go to the school library to study after class.", "课后我们经常去学校图书馆学习。"]},
    "wear": {"sentence": ["He is wearing a white shirt and a pair of blue trousers today.", "他今天穿着一件白衬衫和一条蓝裤子。"]},
    "week": {"sentence": ["There are seven days in a week, and Sunday is the last.", "一周有七天，周日是最后一天。"]},
    "well": {"sentence": ["She can speak English very well after learning it for years.", "学习几年之后，她英语说得很好。"]},
    "What about": {"sentence": ["- I like playing football. - What about you, Peter?", "—我喜欢踢足球。—你呢，彼得？"]},
    "when": {"sentence": ["When did you finish your homework yesterday afternoon?", "昨天下午你几点完成作业的？"]},
    "where": {"sentence": ["Where is my new English dictionary? I can't find it now.", "我的新英语词典在哪儿？我现在找不到它。"]},
    "which": {"sentence": ["Which do you like better, English history or music science?", "你更喜欢哪一个，英语历史还是音乐科学？"]},
    "who": {"sentence": ["Who is that tall boy standing near the library? He is Tom.", "站在图书馆附近的那个高个子男孩是谁？他是汤姆。"]},
    "woman": {"sentence": ["The woman in the red dress is our new English teacher.", "穿红裙子的那位女士是我们的新英语老师。"]},
    "work": {"sentence": ["My father works very hard in a big company every day.", "我父亲每天在一家大公司工作得很努力。"]},
    "worker": {"sentence": ["Many workers are building a new library near our school.", "许多工人正在我们学校附近建一座新图书馆。"]},
    "world": {"sentence": ["English is an important language used all over the world.", "英语是一门在全世界都很受欢迎的重要语言。"]},
    "year": {"sentence": ["He is thirteen years old and lives in a big city in China.", "他十三岁，住在中国的一个大城市。"]},
    "zebra": {"sentence": ["The zebra is a famous animal from Africa with black stripes.", "斑马是来自非洲的一种有着黑色条纹的著名动物。"]},
    "zoo": {"sentence": ["We saw many interesting wild animals in the city zoo yesterday.", "昨天我们在城市动物园见到了许多有趣的野生动物。"]}
}

update_json('sentence/【外研版】七年级上册英语电子课本.json', g7_up_entries_nz)
print("Updated Batch 4b: G7 Up (N-Z).")
