import json
import os

def update_json(filepath, new_entries):
    if not os.path.exists(filepath):
        data = {}
    else:
        with open(filepath, 'r', encoding='utf-8') as f:
            data = json.load(f)
    
    data.update(new_entries)
    
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=4)

# Batch 3a: 七年级下册 (A-M)
g7_down_entries_am = {
    "across": {"sentence": ["Go across the street and you will see the library.", "穿过街道，你就会看到图书馆。"]},
    "adult": {"sentence": ["This movie is more suitable for an adult than a child.", "这部电影比起小孩更适合成年人。"]},
    "African": {"sentence": ["Elephants are famous African animals on the large grassland.", "象是大草原上著名的非洲动物。"]},
    "after": {"sentence": ["We usually have a short break after the third lesson.", "通常在第三节课后我们会有一次短暂休息。"]},
    "Africa": {"sentence": ["My uncle works in Africa and often tells us stories about it.", "我叔叔在非洲工作，经常给我们讲那里的故事。"]},
    "airplane": {"sentence": ["I saw a big airplane flying high in the blue sky.", "我看到一架大飞机在蓝天中高高飞翔。"]},
    "alert": {"sentence": ["The little cat is very alert to any sudden noise.", "那只小猫对任何突然的响声都很警觉。"]},
    "all over the world": {"sentence": ["Football is a popular sport all over the world.", "足球是一项风靡全世界的流行运动。"]},
    "along": {"sentence": ["Walk along this road and turn left at the first corner.", "沿着这条路走，在第一个拐角处向左转。"]},
    "around": {"sentence": ["Let's sit around the table and discuss our weekend plan.", "让我们围坐在桌旁讨论我们的周末计划。"]},
    "arrive": {"sentence": ["What time did you arrive at the school gate this morning?", "今天早上你几点到达校门口的？"]},
    "as": {"sentence": ["He works as a doctor in a big city hospital now.", "他现在在大城市的一家医院当医生。"]},
    "Australia": {"sentence": ["Australia is a beautiful country with many special animals.", "澳大利亚是一个拥有许多特殊动物的美丽国家。"]},
    "Australian": {"sentence": ["My pen friend is Australian and he likes playing cricket.", "我的笔友是澳大利亚人，他喜欢打板球。"]},
    "away": {"sentence": ["Please put your toys away before you go to bed.", "睡觉前请把你的玩具收起来。"]},
    "back": {"sentence": ["He came back home late because of the heavy rain.", "因为大雨，他很晚才回到家。"]},
    "ball": {"sentence": ["The kids are playing with a small colorful ball in the yard.", "孩子们正在院子里玩一个彩色的小球。"]},
    "bamboo": {"sentence": ["Pandas like to eat fresh bamboo and live in the forest.", "大熊猫喜欢吃新鲜竹子，生活在森林里。"]},
    "bank": {"sentence": ["My father goes to the bank to save some money every month.", "我爸爸每个月都去银行存点钱。"]},
    "be born": {"sentence": ["I was born in a small village near the mountains.", "我出生在靠山的一个小村庄。"]},
    "be careful": {"sentence": ["Be careful when you use the sharp knife in the kitchen.", "在厨房里用锋利的刀时要小心。"]},
    "be from": {"sentence": ["Where are you from? I am from a city in China.", "你来自哪里？我来自中国的一个城市。"]},
    "be good at": {"sentence": ["She is very good at drawing beautiful pictures of flowers.", "她非常擅长画美丽的花。"]},
    "beach": {"sentence": ["We spent our summer holiday on a beautiful beach last year.", "去年我们在一片美丽的海滩上度过了暑假。"]},
    "bear": {"sentence": ["The big brown bear is sleeping in a dark cave now.", "那只大棕熊现在正在黑暗的洞穴里睡觉。"]},
    "bedroom": {"sentence": ["My bedroom is small but very comfortable and clean.", "我的卧室虽然小，但非常舒适和干净。"]},
    "before": {"sentence": ["Remember to wash your hands before you have dinner.", "记得在吃晚饭前洗手。"]},
    "best": {"sentence": ["He is my best friend and we often help each other.", "他是我最好的朋友，我们经常互相帮助。"]},
    "big": {"sentence": ["The elephant is a very big animal with a long nose.", "象是一种有着长鼻子的非常大的动物。"]},
    "board": {"sentence": ["The teacher wrote the new words on the blackboard clearly.", "老师在黑板上清晰地写下了新单词。"]},
    "boat": {"sentence": ["We took a small boat to go across the wide river.", "我们坐小船穿过宽阔的河流。"]},
    "born": {"sentence": ["He was born in the winter of nineteen ninety-eight.", "他出生于一九九八年的冬天。"]},
    "breakfast": {"sentence": ["I usually have an egg and a glass of milk for breakfast.", "我早餐通常吃一个鸡蛋并喝一杯牛奶。"]},
    "bridge": {"sentence": ["There is a stone bridge over the river near my home.", "我家附近的河上有一座石桥。"]},
    "bring": {"sentence": ["Please bring your English book to the classroom tomorrow.", "明天请把你的英语书带到教室来。"]},
    "build": {"sentence": ["They decided to build a new library for the children.", "他们决定为孩子们建一座新图书馆。"]},
    "bus stop": {"sentence": ["I usually wait for the bus at the bus stop near my house.", "我通常在离我家很近的公交站等车。"]},
    "buy": {"sentence": ["My mother bought a new schoolbag for me yesterday.", "我妈妈昨天为我买了一个新学包。"]},
    "by bus": {"sentence": ["Many students go to school by bus every morning.", "许多学生每天早晨坐公交车上学。"]},
    "call": {"sentence": ["Can you call me when you reach the airport, please?", "你到达机场时能给我打个电话吗？"]},
    "Camel": {"sentence": ["The camel is an important animal for people in the desert.", "对沙漠里的人来说，骆驼是一种重要的动物。"]},
    "can": {"sentence": ["I can play the piano now after a year of practice.", "练习一年后，我现在会弹钢琴了。"]},
    "careful": {"sentence": ["Please be careful when you cross the busy street.", "横穿繁忙的街道时请务必小心。"]},
    "carry": {"sentence": ["The strong man is carrying a heavy box up the stairs.", "那个强壮的男人正搬着一个重箱子上楼梯。"]},
    "central": {"sentence": ["The central park is a popular place for people to relax.", "中央公园是人们放松的一个常去的地方。"]},
    "check": {"sentence": ["You should check your homework carefully before you hand it in.", "交作业前你应该仔细检查。"]},
    "chess": {"sentence": ["My grandfather and I often play chess on Sunday afternoons.", "我和我祖父常在周日下午下国际象棋。"]},
    "China": {"sentence": ["China is a great country with a long and interesting history.", "中国是一个拥有悠久有趣历史的伟大国家。"]},
    "Chinese": {"sentence": ["Most Chinese people like to drink tea and eat dumplings.", "大多数中国人喜欢喝茶并吃饺子。"]},
    "city": {"sentence": ["I live in a big city with many tall buildings and parks.", "我住在一个有着许多高楼和公园的大城市。"]},
    "classroom": {"sentence": ["The students are cleaning the classroom to make it tidy.", "学生们正在打扫教室使其整洁。"]},
    "clean": {"sentence": ["You should keep your room clean and tidy every day.", "你应该每天保持房间干净整洁。"]},
    "clever": {"sentence": ["The clever boy found a new way to solve the math problem.", "那个聪明的男孩发现了一个解决数学题的新方法。"]},
    "climb": {"sentence": ["They like to climb mountains to enjoy the fresh air.", "他们喜欢爬山以享受新鲜空气。"]},
    "club": {"sentence": ["I joined the music club to learn how to play the guitar.", "我加入了音乐俱乐部去学习弹吉他。"]},
    "collect": {"sentence": ["He likes to collect old coins from different countries.", "他喜欢收集不同国家的旧钱币。"]},
    "colour": {"sentence": ["What is your favourite colour, blue, red or green?", "你最喜欢的颜色是什么，蓝色、红色还是绿色？"]},
    "computer": {"sentence": ["I use the computer to look up information for my project.", "我用电脑为我的项目查找信息。"]},
    "concert": {"sentence": ["We went to an exciting music concert last Saturday night.", "上周六晚上我们去了一场精彩的音乐会。"]},
    "cook": {"sentence": ["My mother cooks delicious food for us every day.", "我妈妈每天为我们做好吃的食物。"]},
    "country": {"sentence": ["The tiger is a very famous animal in this country.", "虎在这个国家是一种非常有名的动物。"]},
    "cousin": {"sentence": ["My cousin will visit us during the next summer holiday.", "我表弟将在下个暑假来看望我们。"]},
    "dance": {"sentence": ["The little girls are learning how to dance in the gym.", "小女孩们正在体育馆学习跳舞。"]},
    "dancer": {"sentence": ["She is a famous dancer who has performed all over the world.", "她是一位在全世界演出的著名舞者。"]},
    "dangerous": {"sentence": ["It is dangerous to play with fire in the forest.", "在森林里玩火是很危险的。"]},
    "day": {"sentence": ["There are seven days in a week, and Sunday is the last.", "一周有七天，周日是最后一天。"]},
    "decide": {"sentence": ["We decided to have a picnic in the park this Sunday.", "我们决定本周日去公园野餐。"]},
    "different": {"sentence": ["People from different countries have different customs.", "来自不同国家的人有着不同的习俗。"]},
    "dinner": {"sentence": ["Our family usually has dinner together at seven o'clock.", "我们全家人通常在七点一起吃晚饭。"]},
    "doctor": {"sentence": ["If you feel ill, you should go to see a doctor immediately.", "如果你感到不适，你应该立即去看医生。"]},
    "down": {"sentence": ["Please sit down and open your books to page ten.", "请坐下，翻开书到第十页。"]},
    "draw": {"sentence": ["The little boy likes to draw pictures of animals in his notebook.", "那个小男孩喜欢在笔记本上画动物。"]},
    "dream": {"sentence": ["My dream is to become a famous singer in the future.", "我的梦想是将来成为一名著名的歌手。"]},
    "drink": {"sentence": ["We should drink plenty of water to stay healthy.", "我们应该喝充足的水以保持健康。"]},
    "drive": {"sentence": ["My father can drive a car but my mother can't.", "我爸爸会开车但他妈妈不会。"]},
    "driver": {"sentence": ["The taxi driver showed us the way to the museum.", "那位出租车司机给我们指明了去博物馆的路。"]},
    "duck": {"sentence": ["There are some white ducks swimming in the small pond.", "有几只白鸭正在小池塘里游泳。"]},
    "during": {"sentence": ["We stayed at my grandparents' house during the holiday.", "假期期间我们待在祖父母家。"]},
    "early": {"sentence": ["He usually gets up early to go for a run in the park.", "他通常起得很早去公园跑步。"]},
    "earthquake": {"sentence": ["The big earthquake destroyed many houses in the small town.", "那场大地震摧毁了小镇上的许多房子。"]},
    "east": {"sentence": ["The sun rises in the east and sets in the west.", "太阳从东方升起，从西方落下。"]},
    "eat": {"sentence": ["Pandas like to eat bamboo and live in the mountains.", "熊猫喜欢吃竹子，生活在大山里。"]},
    "Egypt": {"sentence": ["Egypt is a country famous for its ancient pyramids.", "埃及是一个以其古老金字塔闻名的国家。"]},
    "else": {"sentence": ["What else do we need to buy for the party on Sunday?", "周日的派对我们还需要买点别的什么？"]},
    "email": {"sentence": ["I sent an email to my pen friend in England yesterday.", "昨天我给我在英国的笔友发了一封电子邮件。"]},
    "English": {"sentence": ["English is a very important language used all over the world.", "英语是一门风靡全世界的重要语言。"]},
    "enjoy": {"sentence": ["I hope you will enjoy your stay in our beautiful city.", "希望你在我们这座美丽的城市度过愉快的时光。"]},
    "European": {"sentence": ["Many European countries have a long and interesting history.", "许多欧洲国家有着悠久有趣的历史。"]},
    "every": {"sentence": ["Every student in our class has a new English dictionary.", "我们班每个学生都有一个新的英语词典。"]},
    "excited": {"sentence": ["The children were very excited about the school trip.", "孩子们对学校旅行感到非常兴奋。"]},
    "exciting": {"sentence": ["The football match we watched last night was very exciting.", "我们昨晚看的那场足球赛非常精彩。"]},
    "expensive": {"sentence": ["This new laptop is too expensive for me to buy now.", "这台新电脑太贵了，我现在买不起。"]},
    "face": {"sentence": ["She has a round face and big blue eyes, very cute.", "她有着圆圆的脸和大大的蓝眼睛，非常可爱。"]},
    "family": {"sentence": ["Our family usually goes to the park together on weekends.", "我们家人通常在周末一起去公园。"]},
    "famous": {"sentence": ["Beijing is a famous city with many historical places.", "北京是一个有着许多历史古迹的名城。"]},
    "farm": {"sentence": ["The farmer lives on a large farm with a lot of animals.", "农场主住在一个有着许多动物的大农场里。"]},
    "fast": {"sentence": ["The high-speed train travels very fast to the next city.", "高铁开得很快，正在前往下一个城市。"]},
    "father": {"sentence": ["My father is a teacher and he works very hard every day.", "我父亲是一名老师，他每天工作都很努力。"]},
    "favourite": {"sentence": ["Blue is my favourite colour because it is like the sky.", "蓝色是我最喜欢的颜色，因为它像天空。"]},
    "February": {"sentence": ["February is the shortest month of the year with twenty-eight days.", "二月是一年中最短的一个月，有二十八天。"]},
    "feel": {"sentence": ["I feel very happy whenever I play with my best friends.", "每当我与最好的朋友一起玩耍时，我都感到非常快乐。"]},
    "festival": {"sentence": ["The Spring Festival is the most important festival in China.", "春节是中国最重要的节日。"]},
    "field": {"sentence": ["The children are playing happily in the large green field.", "孩子们正在那片大草地上开心地玩耍。"]},
    "find": {"sentence": ["Can you help me find my lost keys? I left them somewhere.", "你能帮我找找我丢的钥匙吗？我把它们落在某处了。"]},
    "finish": {"sentence": ["You should finish your homework before you go out to play.", "出去玩之前你应该完成作业。"]},
    "fire": {"sentence": ["The fire was very large and destroyed many old buildings.", "火势很大，摧毁了许多古老的建筑物。"]},
    "first": {"sentence": ["Monday is the first day of a week for many people.", "对许多人来说，周一是一周的第一天。"]},
    "flower": {"sentence": ["There are many beautiful flowers in our school garden now.", "现在我们学校花园里有很多美丽的花。"]},
    "food": {"sentence": ["My mother cooks healthy food for our family every day.", "我妈妈每天为家人做健康的食物。"]},
    "foreign": {"sentence": ["I like learning foreign languages and listening to music.", "我喜欢学习外语并听音乐。"]},
    "forest": {"sentence": ["Many wild animals live in the dark and large forest.", "许多野生动物生活在黑暗茂密的森林里。"]},
    "forget": {"sentence": ["Don't forget to close the window when you leave the room.", "离开房间时别忘了关窗。"]},
    "free": {"sentence": ["If you are free this weekend, let's go to the museum.", "如果你本周末有空，我们去博物馆吧。"]},
    "fresh": {"sentence": ["We can enjoy the fresh air in the countryside on weekends.", "周末我们可以在乡下享受新鲜空气。"]},
    "Friday": {"sentence": ["Friday is my favourite day because the weekend is coming.", "周五是我最喜欢的日子，因为周末就要来了。"]},
    "friend": {"sentence": ["He is a kind boy and has many friends in our class.", "他是一个善良的男孩，在我们班有很多朋友。"]},
    "friendly": {"sentence": ["The people in this small town are very friendly to visitors.", "小镇上的人对游客非常友好。"]},
    "from": {"sentence": ["Where is your new English teacher from? She is from London.", "你的新英语老师来自哪里？她来自伦敦。"]},
    "fruit": {"sentence": ["Eating fresh fruit every day is good for your health.", "每天吃新鲜水果对你的健康有好处。"]},
    "future": {"sentence": ["We should work hard now to have a bright and happy future.", "为了有一个光明幸福的未来，我们现在应该努力。"]},
    "game": {"sentence": ["My favorite game is football and I play it with my friends.", "我最喜欢的游戏是足球，我和朋友们一起玩。"]},
    "garden": {"sentence": ["There are many colorful flowers in our school garden now.", "现在我们学校的花园里有很多美丽的花。"]},
    "gate": {"sentence": ["Please wait for me at the school gate at four o'clock.", "请四点钟在校门口等我。"]},
    "get": {"sentence": ["Can you help me get some water from the small kitchen?", "你能帮我从那个小厨房里拿点水来吗？"]},
    "gift": {"sentence": ["His parents gave him a new book as a birthday gift.", "他的父母送给他一本新书作为生日礼物。"]},
    "give": {"sentence": ["Please give this letter to your English teacher tomorrow morning.", "请明天早晨把这封信交给你的英语老师。"]},
    "glass": {"sentence": ["The window is made of glass, so be careful with it.", "窗户是玻璃做的，所以请小心。"]},
    "go": {"sentence": ["We usually go to the library to study on Saturday afternoons.", "我们通常在周六下午去图书馆学习。"]},
    "gold": {"sentence": ["She won a gold medal in the hundred-meter race yesterday.", "昨天她在百米赛跑中获得了一枚金牌。"]},
    "good": {"sentence": ["It is a good habit to read English every morning.", "每天早晨读英语是一个好习惯。"]},
    "grandparent": {"sentence": ["I visit my grandparents in the countryside every summer holiday.", "每个暑假我都会去乡下看望我的祖父母。"]},
    "grass": {"sentence": ["The children are playing happily on the green grass now.", "孩子们现在正在绿草地上开心地玩耍。"]},
    "great": {"sentence": ["We had a great time during our trip to the Great Wall.", "在长城之行中我们度过了一段美好的时光。"]},
    "ground": {"sentence": ["There are many yellow leaves on the ground in autumn.", "秋天地上有很多黄叶。"]},
    "group": {"sentence": ["We worked in a group to finish our science project together.", "我们小组合作一起完成了科学项目。"]},
    "grow": {"sentence": ["Many flowers and trees begin to grow in the early spring.", "许多花木在早春开始生长。"]},
    "grow": {"sentence": ["Many flowers and trees begin to grow in the early spring.", "许多花木在早春开始生长。"]},
    "gym": {"sentence": ["We have our P.E. class in the school gym on rainy days.", "下雨天我们在学校体育馆上体育课。"]},
    "habit": {"sentence": ["Eating breakfast every morning is a very healthy habit.", "每天早晨吃早餐是一个非常健康的习惯。"]},
    "half": {"sentence": ["It's half past eight; we have only ten minutes for class.", "现在是八点半；我们离上课只有十分钟了。"]},
    "happy": {"sentence": ["I felt very happy when I received your beautiful gift.", "当我收到你精美的礼物时，我感到非常开心。"]},
    "hard": {"sentence": ["He worked very hard and passed the difficult math test.", "他学习非常努力，通过了那场很难的数学测试。"]},
    "hard-working": {"sentence": ["She is a hard-working student and always gets good grades.", "她是一个学习努力的学生，总是取得好成绩。"]},
    "head": {"sentence": ["He hit his head against the door when he ran out.", "他跑出去的时候头撞在了门上。"]},
    "healthy": {"sentence": ["Eating more vegetables and fruit is good for a healthy life.", "多吃蔬果有利于健康生活。"]},
    "hear": {"sentence": ["I can hear someone talking in the room next door.", "我可以听到隔壁房间有人在说话。"]},
    "heavy": {"sentence": ["The box is too heavy for the little boy to lift up.", "箱子太重了，小男孩搬不起来。"]},
    "help": {"sentence": ["Can you help me with my English homework this evening?", "今晚你能帮我做英语作业吗？"]},
    "help sb. with sth.": {"sentence": ["My sister often helps me with my math problems at home.", "我姐姐经常在家帮我解决数学难题。"]},
    "here": {"sentence": ["Wait for me here; I will be back in ten minutes.", "在这里等我；我十分钟后就回来。"]},
    "high": {"sentence": ["The airplane is flying high in the blue and clear sky.", "飞机正在湛蓝晴朗的天空中高高飞翔。"]},
    "holiday": {"sentence": ["What are you going to do during the next winter holiday?", "下个寒假你打算做什么？"]},
    "homework": {"sentence": ["I usually finish my homework before I watch TV on Friday.", "周五看电视前我通常先完成作业。"]},
    "hope": {"sentence": ["I hope all of you will have a wonderful summer holiday.", "希望你们所有人都有一个精彩的暑假。"]},
    "hot": {"sentence": ["It is very hot in summer, so we like going swimming.", "夏天很热，所以我们喜欢去游泳。"]},
    "hotel": {"sentence": ["We stayed in a small hotel near the old and quiet library.", "我们住在一家离古老宁静的图书馆不远的小旅馆。"]},
    "how": {"sentence": ["How did you get to the museum yesterday? By bus.", "昨天你。"]},
    "human": {"sentence": ["The study of the human body is very interesting and useful.", "研究人体是非常有趣且有用的。"]},
    "hundred": {"sentence": ["There are about three hundred students in our school now.", "我们学校现在大约有三百名学生。"]},
    "hunt": {"sentence": ["In ancient times, people used to hunt animals for food.", "在古代，人们过去常狩猎动物作为食物。"]},
    "I": {"sentence": ["I am a student and I like reading English books.", "我是一个学生，我喜欢读英语书。"]},
    "idea": {"sentence": ["That's a great idea! Let's go to the park this Sunday.", "那是个好主意！这周日我们去公园吧。"]},
    "if": {"sentence": ["If it rains tomorrow, we will have to stay at home.", "如果明天下雨，我们将不得不待在家里。"]},
    "important": {"sentence": ["Learning English is very important for our future work.", "学习英语对我们未来的工作非常重要。"]},
    "in": {"sentence": ["There are many books in the school library for students.", "学校图书馆里有很多给学生读的书。"]},
    "indeed": {"sentence": ["The story is indeed very interesting and full of magic.", "这个故事确实非常有趣，充满了魔法。"]},
    "inside": {"sentence": ["It is warm inside the room even if it's cold outside.", "即使外面很冷，房间里还是很温暖。"]},
    "instrument": {"sentence": ["The piano is a popular musical instrument all over the world.", "钢琴是一种在全世界都很受欢迎的乐器。"]},
    "into": {"sentence": ["The little cat jumped into the box to hide from us.", "小猫跳进箱子躲着我们。"]},
    "island": {"sentence": ["We went to a beautiful island for our holiday last summer.", "去年夏天我们去了一个美丽的岛屿度假。"]},
    "it": {"sentence": ["I found my lost pen; it was under the small wooden table.", "我找到了丢的笔；它就在那个小木桌下。"]},
    "jacket": {"sentence": ["Put on your jacket; it's a bit cold outside this morning.", "穿上你的夹克；今天早晨外面有点冷。"]},
    "January": {"sentence": ["January is the first month of the year and it's often cold.", "一月是一年中的第一个月，而且通常很冷。"]},
    "Japan": {"sentence": ["Tokyo is the capital of Japan and a very big modern city.", "东京是日本的首都，也是一个非常大的现代化城市。"]},
    "Japanese": {"sentence": ["My uncle likes Japanese food, especially sushi and ramen.", "我叔叔喜欢日本食物，尤其是寿司和拉面。"]},
    "job": {"sentence": ["Her dream is to have an interesting job as a famous doctor.", "她的梦想是成为一名著名医生，拥有一份有趣的工作。"]},
    "join": {"sentence": ["I want to join the school music club to learn the guitar.", "我想加入学校音乐俱乐部学习吉他。"]},
    "journey": {"sentence": ["Our journey to the mountains was very exciting and fun.", "我们的山区之行非常令人兴奋且有趣。"]},
    "juice": {"sentence": ["I usually have a glass of orange juice for my breakfast.", "我早餐通常喝一杯橙汁。"]},
    "July": {"sentence": ["The summer holiday usually begins in early July every year.", "暑假通常在每年的七月初开始。"]},
    "June": {"sentence": ["Children's Day is on the first day of June in our country.", "在我国，儿童节在六月的第一天。"]},
    "just": {"sentence": ["Wait a minute; I am just finishing my English homework.", "等一下；我正在完成英语作业。"]},
    "keep": {"sentence": ["Please keep the classroom clean and tidy after lessons.", "课后请保持教室干净整洁。"]},
    "kind": {"sentence": ["The old lady is very kind and often helps her neighbors.", "那位老太太人很好，经常帮助邻居。"]},
    "know": {"sentence": ["Do you know the name of that tall boy in our class?", "你知道我们班那个高个子男孩的名字吗？"]},
    "lake": {"sentence": ["We took a walk along the quiet lake after dinner yesterday.", "昨天晚饭后我们沿着宁静的湖边散步。"]},
    "language": {"sentence": ["English is a very important language used by many people.", "英语是一门被许多人使用的非常重要的语言。"]},
    "last": {"sentence": ["We went to the beach during our last summer holiday.", "我们在上个暑假去了海滩。"]},
    "later": {"sentence": ["I will call you back ten minutes later to discuss more.", "我会地十分钟后给你回电话以讨论更多内容。"]},
    "laugh": {"sentence": ["Everyone began to laugh when they heard the funny story.", "听到那个有趣的故事后，每个人都开始大笑。"]},
    "leaf": {"sentence": ["The leaves of the trees begin to turn green in early spring.", "早春时节，树叶开始变绿。"]},
    "learn": {"sentence": ["I want to learn how to cook delicious food from my mother.", "我想跟妈妈学习如何做美味的食物。"]},
    "left": {"sentence": ["He wrote his name on the left corner of the small paper.", "他在那张小纸片的左角写下了名字。"]},
    "library": {"sentence": ["We often go to the school library to read books after class.", "课后我们经常去学校图书馆看书。"]},
    "lie": {"sentence": ["The cat likes to lie on the sofa and sleep in the sun.", "那只猫喜欢躺在沙发上晒太阳。"]},
    "life": {"sentence": ["My life in the interactive school is very interesting and fun.", "我在互动学校的生活非常有趣。"]},
    "like": {"sentence": ["I like reading books, especially those about space and animals.", "我喜欢读书，尤其是关于太空和动物的书。"]},
    "line": {"sentence": ["Please wait in a line to get your lunch in the canteen.", "请排队在食堂领午餐。"]},
    "link": {"sentence": ["The teacher shared a useful link for us to learn English.", "老师分享了一个有用的链接供我们学习英语。"]},
    "list": {"sentence": ["Can you make a shopping list for the party this Sunday?", "你能为本周日的派对列一个购物清单吗？"]},
    "listen": {"sentence": ["Please listen to the teacher carefully when she is talking.", "老师讲话时请仔细听讲。"]},
    "listen to": {"sentence": ["I often listen to pop music while I am doing my homework.", "我经常在做作业时听流行音乐。"]},
    "little": {"sentence": ["There is a little bird singing on the tree outside my room.", "我房间外的树上有一只小鸟在唱歌。"]},
    "live": {"sentence": ["I live in a small but very peaceful village near the sea.", "我住在一个靠近大海但非常宁静的小村庄。"]},
    "London": {"sentence": ["London is a very big city and the capital of the UK.", "伦敦是一个非常大的城市，也是英国的首都。"]},
    "long": {"sentence": ["The high-speed train travels very fast to the next city.", "高铁行驶很快，去往下一个城市的行程并不长。"]},
    "look": {"sentence": ["Look! The birds are flying high in the blue and clear sky.", "看！鸟儿正在晴朗的蓝天中高高飞翔。"]},
    "look after": {"sentence": ["Can you help me look after my dog when I am not at home?", "我不在家时，你能帮我照顾我的狗吗？"]},
    "look at": {"sentence": ["Please look at the blackboard and listen to me carefully.", "请看黑板，并仔细听我说。"]},
    "look for": {"sentence": ["I am looking for my English book; have you seen it somewhere?", "我正在寻找我的英语书；你在哪儿看见过吗？"]},
    "lost and found office": {"sentence": ["If you lose your keys, you can go to the lost and found office.", "如果你丢了钥匙，你可以去失物招领处。"]},
    "love": {"sentence": ["I love my family very much and we often go to the park.", "我非常爱我的家人，我们经常去公园。"]},
    "lunch": {"sentence": ["We usually have lunch at twelve o'clock in the canteen.", "我们通常十二点在食堂吃午饭。"]},
    "machine": {"sentence": ["This machine can help people clean the floor easily now.", "现在这台机器能帮助人们轻松地打扫地板。"]},
    "magic": {"sentence": ["The story about the magical forest is very popular now.", "关于魔法森林的故事现在很受欢迎。"]},
    "make": {"sentence": ["My mother makes delicious cakes for us on Sunday mornings.", "我妈妈在周日早晨为我们做美味的蛋糕。"]}
}
update_json('sentence/【外研版】七年级下册英语电子课本.json', g7_down_entries_am)
print("Updated Batch 3a: A-M.")
